### ISSUE TITLE
v1.0 Roadmap

### ISSUE THREAD

**Issue by dandelany** [dandelany/vector-toy#1]
## To Do
- [x] auto-save option
- [x] margin for function labels
- [x] mode label
- [x] tooltip all the things
## Done
- [x] finish new particle system
- [x] true polar mode
- [x] use same functions for cartesian & polar
- [x] add domain setting to control panel
- [x] simple tooltip component
- [x] tooltip text for all controls and parameters
- [x] move timing into flowfield
- [x] style control panel
- [x] save settings in URL?
- [x] expand function inputs on focus
- [x] replaceState instead of pushState
- [x] pushState on Save
- [x] make FlowFieldChart reactochart wrapper for Flowfield, 
- [x] use without reactochart
- [x] google analytics
- [x] rewrite wallpaper component to fit window with control panel
- [x] alert on landscape mode
- [x] meta tag to set mobile width
- [x] control panel on bottom for mobile?
- [x] shuffled presets on page load
- [x] shuffle button to reshuffle
- [x] individual shuffle buttons for each function
- [x] mouseX and mouseY globals
- [x] add lesshat for css compatibility
- [x] mobile: fix tooltip
- [x] mobile: don't resize on zoom
- [x] rename `theta` to `th`
- [x] vx, vy parameters

**Comment by dandelany** [comment]
# Version 1.1 Roadmap

## Fixes
* [ ] bug with line break before return in function boxes

## UI
* [ ] document globals
* [ ] boolean/radio buttons
* [ ] wrap control panel in `react-dock`?
* [ ] locked domain setting
* [ ] number slider
* [ ] scroll to zoom

## Features
* [ ] console.log current state, to make generating preset easier
* [ ] blend mode setting
* [ ] investigate speed improvement from vec2d implementation?
* [ ] add particles on mousedown
* [ ] hide tooltips option
