### ISSUE TITLE
v1.1 Roadmap

### ISSUE THREAD

**Issue by dandelany** [dandelany/vector-toy#2]
## Fixes
- [ ] bug with line break before return in function boxes
## UI
- [ ] document globals
- [ ] boolean/radio buttons
- [ ] wrap control panel in `react-dock`?
- [ ] locked domain setting
- [ ] number slider
- [ ] scroll to zoom
## Features
- [ ] more defaults
- [ ] particle lifespan option
- [ ] particle birthplace option
- [ ] console.log current state, to make generating preset easier
- [ ] blend mode setting
- [ ] investigate speed improvement from vec2d implementation?
- [ ] add particles on mousedown
- [ ] hide tooltips option
